### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by iangetz** [epiclabs-io/hls-analyzer#1]
Hi,

Thanks for making this. It fits what I've looking for but I ran into an issue running it. Hopefully this is the best forum to report this issue.

Command I used:
python3 hls-analyzer.py http://playertest.longtailvideo.com/adaptive/bbbfull/bbbfull320x180.m3u8

Result:
```
      File "hls-analyzer.py", line 35
        print "***** Analyzing variant ({}) *****".format(bw)
                                                 ^
    SyntaxError: invalid syntax
```

I'm running Ubuntu 15.10.

Thanks,
Ian

**Comment by jeoliva** [comment]
Hi @iangetz,

Thanks for reporting this. I am taking a look.

**Comment by aayvazyan-tgm** [comment]
This error is caused by using python3, this project is built on python2.7
