### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by gk1** [epiclabs-io/hls-analyzer#2]
[root@rx1 hls-analyzer]#  python hls-analyzer.py https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8
Master playlist. List of variants:
Traceback (most recent call last):
  File "hls-analyzer.py", line 150, in <module>
    print "\tPlaylist: {}, bw: {}".format(playlist.absolute_uri, playlist.stream_info.bandwidth)
ValueError: zero length field name in format

Python 2.6 on centos 6.7

**Comment by jeoliva** [comment]
Hi @gk1,

Sorry, I can not reproduce this issue in my environment. I am going to setup an environment similar to yours and will try again.

Thanks

**Comment by jeoliva** [comment]
No reproducible here. @gk1, please let me know if error still happen and steps to reproduce it and I will reopen this issue.

Thanks!
