### ISSUE TITLE
not an issue, but a question.

### ISSUE THREAD

**Issue by ksunika** [epiclabs-io/hls-analyzer#5]
Is there a legend about what means what in the hls analyzer report?
For example, what does I - P - B mean in Frames section?

**Comment by jeoliva** [comment]
Hi @ksunika,

That refers to the frame type (I-Frame, P-Frame, B-Frame) that gives you information about how the frame was encoded:

- I-Frame: Intraframe or keyframe. It is coded completely by itself.
- P-Frame: Predictive Frame. Includes just the changes from the previous frame.
- B-Frame: Bi-Predictive Frame. Use differences between current frame and both the preceding and following frames.

You can find more information about this in the following link: https://en.wikipedia.org/wiki/Video_compression_picture_types
